# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

# pipelines > stages > jobs > steps(tasks)

stages:
- stage: BuildStage
  jobs:
  - job: B_Firstjob
    steps:
    - bash: echo B_Firstjob
    displayName: "Run one line script"
  - job: B_Secondjob
    dependsOn: B_Firstjob
    steps:
    - bash: echo B_Secondjob
    - script: echo See www.azure.com
    displayName: "Run multi line script"

- stage: Devstage
  dependsOn: Buildstage
  jobs:
  - job: D_Firstjob
    steps:
    - script: echo D_Firstjob 
  - job: D_Secondjob
    dependsOn: D_Firstjob
    steps:
    - bash: echo D_Secondjob  

- stage: QAstage
  dependsOn: Buildstage
  jobs:
  - job: Q_Firstjob
    steps:
    - script: echo Q_Firstjob 
  - job: Q_Secondjob
    dependsOn: Q_Firstjob
    steps:
    - bash: echo Q_Secondjob  

- stage: Prodstage
  dependsOn:
  - Devstage
  - QAstage
  jobs:
  - job: P_Firstjob
    steps:
    - script: echo P_Firstjob 
  - job: P_Secondjob
    dependsOn: P_Firstjob
    steps:
    - bash: echo P_Secondjob  
