# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

# pipelines > stages > jobs > steps(tasks)

Jobs:
- job: Firstjob
  steps:
  - script: echo First Job!
    displayName: 'Run a one-line script'
  - script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'
- job: SecondJob
  steps:
  - script: echo Second job!
    displayName: 'Run a one line script'
  - script: |
    echo Run a multiline script
    echo www.bhanu.com
    displayName: 'Run a multiline script'
