# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: Buildstage
  jobs:
  - job: firstjob
    steps:
    - bash: echo "Do the build (B_firstjob)""
    displayName: "Run a one-line script "

- stage: Devdeploy
  jobs: 
  - job: firstjob
    steps:
    - bash: echo "Deploy to Dev (D_firstjob)""
    displayName: "Run a one-line script" 

  - deployment: Devdeployjob
    environment: Dev
    strategy:
     runOnce:
      deploy:
       steps:
       - bash: echo "Do the Deploy (D_delpoyment)""

- stage: QA
  jobs:
  - deployment: QAdeployjob
    environment: QA
    strategy:
     runOnce:
      deploy:
       steps:
       - script: echo "Do the QA (QA_deployment)




