# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

#pipelines > stages > jobs > steps(tasks)

stages:
- stage: Buildstage
  variables:
   environment: Building
  jobs:
  - job: firstjob
    steps:
    - bash: echo "Do the $(environment) (B_firstjob)"
    displayName: "Run a one-line script"

- stage: Devdeploy
  variables:
   environment: Development
  jobs: 
  - job: firstjob
    steps:
    - bash: echo "Deploy to $(environment) (D_firstjob)"
    displayName: "Run a one-line script" 

  - deployment: Devdeployjob
    environment: Dev
    strategy:
     runOnce:
      deploy:
       steps:
       - bash: echo "Do the $(environment) (D_delpoyment)"

- stage: QA
  variables: 
   environment: Quality Assurance
  jobs:
  - deployment: QAdeployjob
    environment: QA
    strategy:
     runOnce:
      deploy:
       steps:
       - script: echo "Do the $(environment) (QA_deployment)"




