# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

# pipelines > stages > jobs > steps (tasks)

stages:
- stage: Build
  jobs:
  - job: Firstjob
    steps:
    - script: echo Build Firstjob!
    - bash: echo $(PipelineLevelVariable)
    - bash: echo $(Build.BuildID)
    - bash: echo $(Build.BuildNumber)
    - bash: echo $(Build.SourceBranchName)
    - bash: echo $(Build.SourcesDirectory)
    - bash: echo $(Build.SourceVersion)
    - bash: echo $(Build.BuildUri)
    - bash: echo $(System.DefaultWorkingDirectory)
    - bash: ls -R $(System.DefaultWorkingDerectory)
    - bash: echo $(Build.ArtifactStagingDirectory)
    - bash: java -version
    - bash: python --version
    - bash: mvn --version
    - bash: node --version
    displayName: 'Run a one-line script'
 #   - bash: ls -R $(System.ArtifactStagingDirectory)
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: |
          **/*.yml
          **/*tf
        TargetFolder: '$(System.ArtifactStagingDirectory)'
    - bash: echo ls -R $(System.ArtifactStagingDirectory)  
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'


